// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKa3rOLICkAPfCRyNfUXM6ZkRkiFOzGXk',
    appId: '1:995646826756:web:c9d5c74993b524e5d18851',
    messagingSenderId: '995646826756',
    projectId: 'farming-ea',
    authDomain: 'farming-ea.firebaseapp.com',
    storageBucket: 'farming-ea.appspot.com',
    measurementId: 'G-FQ03H8G3NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWqkG5u17KfCorQ5Y7iX_1dKO5F0GdhVs',
    appId: '1:995646826756:android:8c5bb234d0d817d8d18851',
    messagingSenderId: '995646826756',
    projectId: 'farming-ea',
    storageBucket: 'farming-ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRFlLzgEfw6VQZZXGrYr87zxtt_oLQvc',
    appId: '1:995646826756:ios:055c7c579b8636e1d18851',
    messagingSenderId: '995646826756',
    projectId: 'farming-ea',
    storageBucket: 'farming-ea.appspot.com',
    iosBundleId: 'com.example.farmingEaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnRFlLzgEfw6VQZZXGrYr87zxtt_oLQvc',
    appId: '1:995646826756:ios:055c7c579b8636e1d18851',
    messagingSenderId: '995646826756',
    projectId: 'farming-ea',
    storageBucket: 'farming-ea.appspot.com',
    iosBundleId: 'com.example.farmingEaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKa3rOLICkAPfCRyNfUXM6ZkRkiFOzGXk',
    appId: '1:995646826756:web:fb3920dbe2fbc6a2d18851',
    messagingSenderId: '995646826756',
    projectId: 'farming-ea',
    authDomain: 'farming-ea.firebaseapp.com',
    storageBucket: 'farming-ea.appspot.com',
    measurementId: 'G-783SZ47E7K',
  );
}
